export const FETCH_USER = 'FETCH_USER';
export const LOGOUT = 'LOGOUT';
export const SET_SIZE = 'SET_SIZE';
export const SET_HISTORY = 'SET_HISTORY';
export const FETCH_INITIATIVES = 'FETCH_INITIATIVES';
export const FETCH_MORE_INITIATIVES = 'FETCH_MORE_INITIATIVES';
export const SET_SEARCH = 'SET_SEARCH';
export const UPDATE_BASIC_USER_DATA = 'UPDATE_BASIC_USER_DATA';
export const ADD_USER_INITIATIVE = 'ADD_USER_INITIATIVE';

// userModules
export const ADD_USER_MODULE = 'ADD_USER_MODULE';
export const UPDATE_USER_MODULE = 'UPDATE_USER_MODULE';
export const DELETE_USER_MODULE = 'DELETE_USER_MODULE';

// publicProfile
export const GET_USER_PUBLIC_PROFILE = 'GET_USER_PUBLIC_PROFILE';
export const CLEAN_PUBLIC_PROFILE = 'CLEAN_PUBLIC_PROFILE';
